# Generated by Django 4.1.1 on 2022-10-28 12:23

from django.db import migrations, models
import django_cryptography.fields
import medimode.models.user_models


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP_seed',
            field=django_cryptography.fields.encrypt(models.TextField(default=medimode.models.user_models.gen_otpseed)),
        ),
    ]
