# Generated by Django 4.1.1 on 2022-10-26 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medimode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='uploads/documents')),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medimode.profile')),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('medimode.profile',),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medimode.profile')),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('medimode.profile',),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medimode.profile')),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('medimode.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medimode.profile')),
                ('medical_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_patient', to='medimode.document')),
                ('proof_of_address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poa_%(class)s', to='medimode.document')),
                ('proof_of_identity', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poi_%(class)s', to='medimode.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('medimode.profile',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medimode.profile')),
                ('medical_license', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owner_doctor', to='medimode.document')),
                ('proof_of_address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poa_%(class)s', to='medimode.document')),
                ('proof_of_identity', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poi_%(class)s', to='medimode.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('medimode.profile',),
        ),
    ]
