# Generated by Django 4.1.1 on 2022-10-26 06:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medimode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='uploads/documents')),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('medical_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_patient', to='medimode.document')),
                ('proof_of_address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poa_%(class)s', to='medimode.document')),
                ('proof_of_identity', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poi_%(class)s', to='medimode.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('image0', models.ImageField(upload_to='uploads/images/')),
                ('image1', models.ImageField(upload_to='uploads/images/')),
                ('location', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owner_doctor', to='medimode.document'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='proof_of_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poa_%(class)s', to='medimode.document'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='proof_of_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='poi_%(class)s', to='medimode.document'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
