# Generated by Django 4.1.1 on 2022-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0002_user_otp_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareable',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='can_access', to='medimode.profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='shareables',
            field=models.ManyToManyField(blank=True, related_name='owner_ticket', to='medimode.ticket_shareable'),
        ),
    ]
