# Generated by Django 4.1.1 on 2022-11-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0003_alter_shareable_shared_with_alter_ticket_shareables'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_hash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
