# Generated by Django 4.1.1 on 2022-11-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0006_user_stripe_acct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image0',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img0_%(class)s', to='medimode.document'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img1_%(class)s', to='medimode.document'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='image0',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img0_%(class)s', to='medimode.document'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='image1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img1_%(class)s', to='medimode.document'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='image0',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img0_%(class)s', to='medimode.document'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='image1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='img1_%(class)s', to='medimode.document'),
        ),
    ]
