# Generated by Django 4.1.1 on 2022-11-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0007_alter_hospital_image0_alter_hospital_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='works_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='worker_doctor', to='medimode.hospital'),
        ),
        migrations.AlterField(
            model_name='shareable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shareables', to='medimode.profile'),
        ),
    ]
