# Generated by Django 4.1.1 on 2022-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0008_doctor_works_at_alter_shareable_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
