# Generated by Django 4.1.1 on 2022-11-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimode', '0009_user_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_hash',
        ),
    ]
