# Generated by Django 4.1.1 on 2022-11-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
